modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
modId="wan_ancient_beasts"
#TODO: you need to add here the version too, the property won't work if gradle isn't setted up correctly, and it's a pain to do it lol
version="0.1.1"
displayName="Wan Ancient Beasts"
logoFile="wan_ancient_beasts_logo.png"
credits="Thanks to the Wan Mine community"
authors="Wanmine Studio"
description="Wan Ancient Beasts Mod"
[[dependencies.wan_ancient_beasts]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wan_ancient_beasts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"